let responseList = [
    `I'm rubber you're glue.`,
    `Oh ho HO! Scathing..`,
    `I hate you so much`,
    `I'm shaking, i'm shaking!`,
    `Oh yeah?`,
    'Your whole family is stupid.',
    'You must have been full of crap.',
    'How appropriate. You fight like a cow!',
    `And I've got a little TIP for you, get the POINT?`,
    `I'm glad to hear you attended your family reunion!`,
    `First you'd better stop waving it like a feather duster.`,
    `Even BEFORE they smell your breath?`,
    `Your hemorrhoids are flaring up again eh?`,
    `He must have taught you everything you know.`,
    `You run THAT fast?`,
    `Why? Did you want to borrow one?`,
    `Yes, there are. You just never learned them.`,
    `You make me think somebody already did.`,
    `So you got that job as janitor, after all.`,
    `I hope now you've learned to stop picking your nose.`,
    `I'd be in real trouble if you ever used them.`,
    `I wanted to make sure you'd feel comfortable with me.`,
]